Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - config/puma.rb
    - config/application.rb
    - db/seeds.rb
    - app/controllers/graphql_controller.rb
    - config/environments/production.rb
    - config/initializers/cors.rb
    - spec/spec_helper.rb
Metrics/BlockLength:
  Exclude:
    - spec/builders/aws/s3/avatar_builder_spec.rb
    - spec/models/user_spec.rb
    - spec/services/aws/s3/avatars_uploader_spec.rb
Metrics/MethodLength:
  Exclude:
    - app/validators/user_validator.rb
