Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - config/puma.rb
    - config/application.rb
    - db/seeds.rb
    - app/controllers/graphql_controller.rb
    - config/environments/production.rb
    - config/initializers/cors.rb
    - spec/spec_helper.rb
Metrics/BlockLength:
  Exclude:
    - spec/builders/aws/s3/avatar_builder_spec.rb
    - spec/models/user_spec.rb
    - spec/services/aws/s3/avatars_uploader_spec.rb
    - spec/graphql/mutations/user/register_user_spec.rb
Metrics/MethodLength:
  Exclude:
    - app/validators/user_validator.rb
    - db/migrate/20221012092230_create_orders.rb
    - app/services/seed_generator/users.rb
    - app/services/seed_generator/products.rb
    - app/services/seed_generator/product_cathegories.rb
    - app/services/seed_generator/opinions.rb
Style/FrozenStringLiteralComment:
  Exclude:
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/update
Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update
Style/HashSyntax:
  Exclude:
    - lib/tasks/send_newsletter.rake
