default: &default
  adapter: postgresql
  encoding: unicode
  username: michsiw439
  password: Ab47901825
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: olx-backend_development

test:
  <<: *default
  database: olx-backend_test

production:
  <<: *default
  database: olx-backend_production
  username: olx-backend
  password: <%= ENV['OLX-BACKEND_DATABASE_PASSWORD'] %>
